[[redirects]]
  from = "/docs/*"
  to = "/docs.html"
  status = 200

[[redirects]]
  from = "/gsheet-template"
  to = "https://docs.google.com/spreadsheets/d/1EiCDzJKdLMGCyLsaFQS3-zvsjmVSMscdVI3FlNgdp8Y/copy"
  status = 301