import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // docs: [{ type: "autogenerated", dirName: "." }],

  // But you can create a sidebar manually

  docs: [
    "intro",
    "getting-started",
    {
      type: "category",
      label: "Setup guides",
      items: [
        "setup_guides/official_template",
        "setup_guides/install_uninstall",
        "setup_guides/configuration",
        "setup_guides/locale",
      ],
    },
    {
      type: "category",
      label: "Core features",
      items: [
        "core/transactions",
        "core/trades",
        "core/dashboard",
        "core/open_positions_summary",
        "core/closed_positions_summary",
      ],
    },
    {
      type: "category",
      label: "Advanced features",
      items: ["advanced/multi_currencies", "advanced/locale"],
    },
    "faq",
    "troubleshooting",
  ],
};

export default sidebars;
